stages:
  - test
  - build
  - deploy

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test
    - echo "Test complete"

build-job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
  script:
  - echo "Building application..."
  - docker-compose build
  - echo "Application successfully builded."

deploy-job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
  script:
    - echo "Deploying application..."
    - docker-compose down
    - docker-compose up -d
    - echo "Application successfully deployed."
    - echo "Remove all unused containers, networks, images (both dangling and unused) and volumes..."
    - docker system prune -f --volumes --all
    - echo "Cleaning complete"
