version: "3"

services:

  postgres:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tezea
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 3308:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mp_tezea -d tezea"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: tezea-dbtools 
    build: # to build image with docker-compose
      context: .
      dockerfile: ./Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tezea.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      GITHUB_CLIENT_ID: '' # use direct login locally
      GITHUB_CLIENT_SECRET: '' # use direct login locally
    read_only: true
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-tmp:/tmp
    ports:
      - 5055:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  pgadmin-data:
  pgadmin-tmp:






